server {
    listen 80;
    server_name eisals.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 'EISALS: Configuring SSL... Wait 30 seconds and reload the page.';
        add_header Content-Type text/plain;
    }
}
